# GitHub Actions Workflow
# CI/CD - Tests de Sécurité Licence USB Video Vault

name: License Security Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Tests quotidiens à 2h du matin UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Permettre déclenchement manuel

env:
  NODE_VERSION: '18'
  VAULT_PATH: 'test-vault'

jobs:
  license-security-tests:
    name: Tests de Sécurité Licence
    runs-on: windows-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        test-scenario:
          - valid-license
          - invalid-signature  
          - expired-license
      fail-fast: false
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install Dependencies
        run: |
          npm ci --prefer-offline --no-audit
          
      - name: Verify Project Structure
        run: |
          echo "📁 Vérification structure projet..."
          if (-not (Test-Path "scripts/make-license.mjs")) {
            throw "Script make-license.mjs manquant"
          }
          if (-not (Test-Path "tests/license-security.test.js")) {
            throw "Script de test license-security.test.js manquant"
          }
          Write-Host "✅ Structure projet valide"
        shell: pwsh
        
      - name: Setup Test Environment
        run: |
          echo "🔧 Configuration environnement de test..."
          
          # Créer environnement de test isolé
          New-Item -Path "$env:VAULT_PATH" -ItemType Directory -Force
          New-Item -Path "$env:VAULT_PATH\.vault" -ItemType Directory -Force
          New-Item -Path "test-results" -ItemType Directory -Force
          New-Item -Path "out" -ItemType Directory -Force
          
          # Variables d'environnement pour les tests
          echo "VAULT_PATH=$env:VAULT_PATH" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          echo "APP_EXECUTABLE=dist/win-unpacked/USB Video Vault.exe" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          echo "CI=true" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          
          Write-Host "✅ Environnement de test configuré"
        shell: pwsh
        
      - name: Build Application
        run: |
          echo "🔨 Build de l'application..."
          npm run build
          
          # Vérifier que l'app est buildée (optionnel pour les tests de licence)
          if (Test-Path "dist") {
            Write-Host "✅ Application buildée avec succès"
          } else {
            Write-Host "⚠️ Build non trouvé, les tests de licence continueront"
          }
        shell: pwsh
        
      - name: Run License Security Tests
        run: |
          echo "🧪 Exécution tests sécurité licence..."
          npm run test:license-security
        env:
          VAULT_PATH: ${{ env.VAULT_PATH }}
          APP_EXECUTABLE: ${{ env.APP_EXECUTABLE }}
          CI: true
        shell: pwsh
        
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: license-test-results-${{ matrix.test-scenario }}
          path: |
            test-results/
            ${{ env.VAULT_PATH }}/
          retention-days: 30
          
      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: license-test-logs-${{ matrix.test-scenario }}-${{ github.run_number }}
          path: |
            test-results/
            out/
            *.log
          retention-days: 7

  aggregate-results:
    name: Agrégation Résultats
    runs-on: windows-latest
    needs: license-security-tests
    if: always()
    
    steps:
      - name: Download All Test Results
        uses: actions/download-artifact@v4
        with:
          pattern: license-test-results-*
          merge-multiple: true
          path: all-results/
          
      - name: Analyze Results
        run: |
          echo "📊 Analyse des résultats de tests..."
          
          $resultFiles = Get-ChildItem -Path "all-results" -Filter "*.json" -Recurse
          $totalTests = 0
          $passedTests = 0
          $failedTests = 0
          
          foreach ($file in $resultFiles) {
            try {
              $result = Get-Content $file.FullName | ConvertFrom-Json
              $totalTests += $result.summary.totalTests
              $passedTests += $result.summary.passedTests
              $failedTests += $result.summary.failedTests
              
              Write-Host "📄 $($file.Name): $($result.summary.passedTests)/$($result.summary.totalTests) réussis"
            } catch {
              Write-Host "⚠️ Erreur lecture $($file.Name): $($_.Exception.Message)"
            }
          }
          
          $successRate = if ($totalTests -gt 0) { [math]::Round(($passedTests / $totalTests) * 100, 2) } else { 0 }
          
          Write-Host ""
          Write-Host "🎯 RÉSULTATS GLOBAUX:"
          Write-Host "   Total tests: $totalTests"
          Write-Host "   Réussis: $passedTests"
          Write-Host "   Échoués: $failedTests"
          Write-Host "   Taux de réussite: $successRate%"
          
          # Sauvegarder résumé pour badge
          $summary = @{
            totalTests = $totalTests
            passedTests = $passedTests
            failedTests = $failedTests
            successRate = $successRate
            timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
            status = if ($failedTests -eq 0) { "SUCCESS" } else { "FAILURE" }
          } | ConvertTo-Json
          
          Set-Content -Path "test-summary.json" -Value $summary
          
          # Définir le statut de sortie
          if ($failedTests -gt 0) {
            Write-Host "❌ ÉCHEC: $failedTests test(s) ont échoué"
            exit 1
          } else {
            Write-Host "✅ SUCCÈS: Tous les tests de sécurité licence passent"
            exit 0
          }
        shell: pwsh
        
      - name: Upload Aggregated Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: license-security-summary
          path: |
            test-summary.json
            all-results/
          retention-days: 90

  notification:
    name: Notification Résultats
    runs-on: ubuntu-latest
    needs: [license-security-tests, aggregate-results]
    if: always() && (github.event_name == 'schedule' || github.event_name == 'push')
    
    steps:
      - name: Notify Results
        run: |
          echo "📧 Notification des résultats..."
          
          if [[ "${{ needs.aggregate-results.result }}" == "success" ]]; then
            echo "✅ Tous les tests de sécurité licence ont réussi"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Certains tests de sécurité licence ont échoué"
            echo "status=failure" >> $GITHUB_OUTPUT
          fi
          
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Déclencheur: ${{ github.event_name }}"
        id: notification
        
      - name: Create Issue on Failure
        if: failure() && github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🚨 Échec Tests Sécurité Licence - ' + new Date().toISOString().split('T')[0];
            const body = `
            ## 🚨 Tests de Sécurité Licence Échoués
            
            **Détails:**
            - Commit: \`${{ github.sha }}\`
            - Branch: \`${{ github.ref_name }}\`
            - Date: ${new Date().toISOString()}
            - Workflow: ${{ github.workflow }}
            
            **Actions requises:**
            1. Examiner les logs de test dans les artefacts
            2. Vérifier l'intégrité du système de licence
            3. Corriger les problèmes identifiés
            4. Re-exécuter les tests
            
            **Liens utiles:**
            - [Logs de test](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - [Documentation](docs/CI_LICENSE_SECURITY_TESTS.md)
            
            ---
            *Ticket créé automatiquement par le workflow CI*
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['bug', 'security', 'license', 'ci-failure']
            });

# Configuration des badges de statut
# Ajouter dans le README.md:
# [![License Security Tests](https://github.com/OWNER/REPO/workflows/License%20Security%20Tests/badge.svg)](https://github.com/OWNER/REPO/actions?query=workflow%3A%22License+Security+Tests%22)